### ISSUE TITLE
bug in resi_pe.geeglm

### ISSUE THREAD

**Issue by KaidiK** [statimagcoll/RESI#9]
sometimes the function `geeglm` will return t statistics instead of "Wald". So it may report error "Error in x[, "Wald"] : subscript out of bounds"

**Comment by KaidiK** [comment]
it seemed that when we have categorical variable(s) having more than 2 levels, it will return t-statistics.

**Comment by MeganTJ21** [comment]
` x[, "Wald"]` is no longer being called
